version: "3.9"

services:

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
    volumes:
      - /mnt/data/MediaServer/config/jellyfin:/config
      - /mnt/data/MediaServer/data:/data
    ports:
      - "8096:8096"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/MediaServer/config/sonarr:/config
      - /mnt/data/MediaServer/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/MediaServer/config/radarr:/config
      - /mnt/data/MediaServer/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/MediaServer/config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - WEBUI_PORT=8080
    volumes:
      - /mnt/data/MediaServer/config/qbittorrent:/config
      - /mnt/data/MediaServer/data:/data
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Australia/Adelaide
    ports:
      - "8191:8191"
    restart: unless-stopped

